# -*- coding: utf-8 -*-
"""assignment3 theoretrical.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kOZoX3kZVQ9z-mGEncpmAEA0E0KHmklS
"""

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import bernoulli
import math
from scipy import stats

prob_trans_white= 1/3
prob_trans_black= 2/3
x=['white ball','black ball']
h=[prob_trans_white,prob_trans_black]
plt.bar(x,h)
plt.xlabel("X")
plt.ylabel("Probability")
plt.title("(Theoretrical)probability of transfered ball(from bag S)")
plt.show()
#when black is trasfered
prob_white1=5/9
prob_black1=4/9
#when white is trasfered
prob_white2=6/9
prob_black2=3/9
prob_white=prob_trans_white*prob_white2+prob_trans_black*prob_white1
prob_black=prob_trans_white*prob_black2+prob_trans_black*prob_black1
print(f'Theoretrical probability of white drawn={prob_white:.2f}')
print(f'Theoretrical probability of black drawn={prob_black:.2f}')
#P(A)=P(A/B)P(B)+P(A/C)P(C)
#Here event A:drawing white ball from bag T
# event B:transferring white ball from bag S to T
# event c:transferring black ball from bag S to T
x=['white ball','black ball']
h=[prob_white,prob_black]
plt.bar(x,h)
plt.xlabel("X")
plt.ylabel("Probability")
plt.title("(Theoretrical)probability of drawn ball(from bag T)")
plt.show()